baseURL = 'https://phenomenal-quokka-4693fb.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-theme-terminal"
googleAnalytics = "UA-227859219-1"

[menu]
    [[menu.main]]
        identifier = "intro"
        name = "intro"
        url = "/intro/"
        weight = 0
    [[menu.main]]
        identifier = "second"
        name = "second"
        url = "/second/"
        weight = 1
  